version: "3"

services:
  db:
    container_name: mysql_rentbike
    image: mysql:latest
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./db_sql:/var/lib/mysql_run
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=rent_bike
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
